from django.urls import re_path
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = [
    re_path(r"^flag/(?P<pk>[0-9]+)/$", views.flag),
    re_path(r"^flag/(?P<pk>[0-9]+)/complete/$", views.markFlagAsDone),
    re_path(r"^flags/$", views.flags),
    re_path(r"^hit/(?P<pk>[0-9]+)/$", views.hit),
    re_path(r"^hit/(?P<pk>[0-9]+)/cvss3/$", views.cvss3_hit),
    re_path(r"^hit/(?P<pk>[0-9]+)/cvss4/$", views.cvss4_hit),
    re_path(r"^hit/(?P<pk>[0-9]+)/comments/$", views.comments),
    re_path(r"^hit/(?P<pk>[0-9]+)/references/$", views.hit_references),
    re_path(r"^hits/$", views.hits),
    re_path(r"^label/(?P<pk>[0-9]+)/$", views.label),
    re_path(r"^labels/$", views.labels),
    re_path(r"^tool/(?P<pk>[0-9]+)/$", views.tool),
    re_path(r"^tools/$", views.tools),
    re_path(r"^attackscenario/(?P<pk>[0-9]+)/$", views.attackscenario),
    re_path(r"^attackscenarios/$", views.attackscenarios),
    re_path(r"^recommendation/(?P<pk>[0-9]+)/$", views.recommendation),
    re_path(r"^recommendations/$", views.recommendations),
    re_path(r"^comment/(?P<pk>[0-9]+)/$", views.comment),
    re_path(r"^hitreference/(?P<pk>[0-9]+)/$", views.hit_reference),
    re_path(r"^screenshot/(?P<pk>[0-9]+)/$", views.screenshot),
    re_path(
        r"^screenshot/(?P<pk>[0-9]+)/order/(?P<order>[0-9]+)/$", views.screenshot_order
    ),
    re_path(r"^screenshot/png/(?P<pk>[0-9]+)/$", views.screenshot_raw),
    re_path(r"^screenshots/$", views.screenshots),
    re_path(r"^archives/$", views.archives),
    re_path(r"^attachment/(?P<pk>[0-9]+)/$", views.attachment),
    re_path(r"^attachment/raw/(?P<pk>[0-9]+)/$", views.attachment_raw),
    re_path(r"^attachments/$", views.attachments),
    re_path(r"^host/(?P<pk>[0-9]+)/$", views.host),
    re_path(r"^hosts/$", views.hosts),
    re_path(r"^service/(?P<pk>[0-9]+)/$", views.service),
    re_path(r"^services/$", views.services),
    re_path(r"^cvss3/$", views.cvss3),
    re_path(r"^cvss4/$", views.cvss4),
    re_path(r"^assessment/(?P<pk>[0-9]+)/$", views.assessment),
    re_path(r"^assessments/$", views.assessments),
    re_path(r"^project/(?P<pk>[0-9]+)/$", views.project),
    re_path(r"^project/(?P<pk>[0-9]+)/burp$", views.project_burp_configuration),
    re_path(r"^project/(?P<pk>[0-9]+)/xlsx$", views.project_xlsx),
    re_path(r"^project/(?P<pk>[0-9]+)/latex$", views.project_latex),
    re_path(r"^project/(?P<pk>[0-9]+)/json$", views.project_json),
    re_path(r"^projects/$", views.projects),
    re_path(r"^template/(?P<pk>[0-9]+)/$", views.template),
    re_path(r"^templates/$", views.templates),
    re_path(r"^case/(?P<pk>[0-9]+)/$", views.case),
    re_path(r"^cases/$", views.cases),
    re_path(r"^module/(?P<pk>[0-9]+)/$", views.module),
    re_path(
        r"^module/(?P<pk>[0-9]+)/load/(?P<assessmentId>[0-9]+)/$", views.load_module
    ),
    re_path(r"^modules/$", views.modules),
    re_path(r"^methodology/(?P<pk>[0-9]+)/$", views.methodology),
    re_path(r"^methodologies/$", views.methodologies),
    re_path(r"^cwes/(?P<pk>[0-9]+)/$", views.cwe_list),
    re_path(r"^cwes/$", views.cwe_lists),
    re_path(r"^cwe/(?P<pk>[0-9]+)/$", views.cwe),
    re_path(r"^cwe/$", views.cwes),
    re_path(r"^token/$", views.manage_token),
    re_path(r"^account/change_password/$", views.change_password),
    re_path(r"^chatgpt/$", views.chatgpt),
    re_path(r"^audit/$", views.audit),
    re_path(r"^retestcampaign/(?P<pk>[0-9]+)/$", views.retestcampaign),
    re_path(r"^retestcampaigns", views.retestcampaigns),
    re_path(r"^retesthit/(?P<pk>[0-9]+)/$", views.retesthit),
    re_path(r"^retesthits/$", views.retesthits),
    re_path(r"^retestscreenshot/(?P<pk>[0-9]+)/$", views.retestscreenshot),
    re_path(
        r"^retestscreenshot/(?P<pk>[0-9]+)/order/(?P<order>[0-9]+)/$",
        views.retestscreenshot_order,
    ),
    re_path(r"^retestscreenshot/png/(?P<pk>[0-9]+)/$", views.retestscreenshot_raw),
    re_path(r"^retestscreenshots/$", views.retestscreenshots),
]
urlpatterns = format_suffix_patterns(urlpatterns)
